name: REUSE
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  reuse:
    name: REUSE
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-reuse.yml@8a67b83aedd4176c2629ac2cb6c9f53041c23abd # v0.1.0
