name: zizmor
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
jobs:
  zizmor:
    name: Zizmor
    permissions:
      contents: read
    uses: openbunny/.github/.github/workflows/reusable-zizmor.yml@8a67b83aedd4176c2629ac2cb6c9f53041c23abd # v0.1.0
    with:
      version: 1.30.1
